baseURL = 'https://unsafe9.github.io/'
languageCode = 'en-us'
title = 'Tech Blog'
theme = 'techblog'

# Enable emoji support
enableEmoji = true

# Pagination
[pagination]
  pagerSize = 10

# Syntax highlighting
[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Taxonomies
[taxonomies]
  tag = 'tags'

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']

# RSS Configuration
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "feed"

# Site Parameters
[params]
  description = 'A personal tech blog about software development and technology'
  author = 'unsafe9'

  # Profile icon (add your profile image to static/images/profile.png)
  profileIcon = '/images/profile.png'

  # Social links
  [params.social]
    github = 'https://github.com/unsafe9'
    linkedin = 'https://linkedin.com/in/yourprofile'
    email = 'mailto:your@email.com'

  # Giscus comments configuration (optional - configure later)
  # Visit https://giscus.app to generate your configuration
  # [params.giscus]
  #   repo = 'your-username/your-repo'
  #   repoId = 'your-repo-id'
  #   category = 'General'
  #   categoryId = 'your-category-id'
  #   mapping = 'pathname'
  #   strict = '0'
  #   reactionsEnabled = '1'
  #   emitMetadata = '0'
  #   inputPosition = 'bottom'
  #   theme = 'light'
  #   lang = 'en'

# Menu configuration (optional)
# [menu]
#   [[menu.main]]
#     name = 'Home'
#     url = '/'
#     weight = 1
#   [[menu.main]]
#     name = 'Tags'
#     url = '/tags/'
#     weight = 2
